# CI-CD doc: https://www.youtube.com/watch?v=QP0pi7xe24s

name: Publish to Azure 

on: 
  workflow_dispatch: # run action manually on deamand
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: WebAppBigPicture
  AZURE_WEBAPP_PACKAGE_PATH: ./WebAppASP.NET/publish


jobs:
  Restore-Build-Publish:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Checkout GitHub Action
        uses: actions/checkout@main


      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'


      - name: Restore
        run: dotnet restore ./WebAppASP.NET/WebAppASP.NET.sln


      - name: Build
        run: dotnet build ./WebAppASP.NET/WebAppASP.NET.sln --configuration Release --no-restore
      

      - name: Publish
        run: dotnet publish ./WebAppASP.NET/WebAppASP.NET.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ''
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          #slot-name: Production
